### ISSUE TITLE
Sending angry emojis causes the bot to crash with the following error:

### ISSUE THREAD

**Issue by Woife5** [Woife5/discord-bots-ts#18]
angry-bot    | Bot is logged in and ready!
angry-bot    | MongoServerError: Updating the path 'emojis.3' would create a conflict at 'emojis'
angry-bot    |     at Connection.onMessage (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:210:30)
angry-bot    |     at MessageStream.<anonymous> (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:63:60)
angry-bot    |     at MessageStream.emit (node:events:390:28)
angry-bot    |     at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
angry-bot    |     at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
angry-bot    |     at writeOrBuffer (node:internal/streams/writable:389:12)
angry-bot    |     at _write (node:internal/streams/writable:330:10)
angry-bot    |     at MessageStream.Writable.write (node:internal/streams/writable:334:10)
angry-bot    |     at Socket.ondata (node:internal/streams/readable:754:22)
angry-bot    |     at Socket.emit (node:events:390:28) {
angry-bot    |   ok: 0,
angry-bot    |   code: 40,
angry-bot    |   codeName: 'ConflictingUpdateOperators',
angry-bot    |   [Symbol(errorLabels)]: Set(0) {}
angry-bot    | }

**Comment by Woife5** [comment]
fixed in abda4f2898499fa47411fba563708b433c73c282
